services:
  wiremock:
    container_name: wiremock
    image: wiremock/wiremock:latest
    ports:
      - "8080:8080"
    volumes:
      - ./files/:/home/wiremock/__files/
      - ./mappings:/home/wiremock/mappings/
